### PR TITLE
Validations

### PR DESCRIPTION
**Pull request by BonkeGcobo**
## Description

- [x] Added Validatons
- [x] Wrote Unit Test for models
- [x] Not really sure about this, but  I think I might have applied the N+1 rule in the previous repo

Happy Reviewing

### CODE REVIEW

**Review by FrederickMih — CHANGES_REQUESTED** [review]
Hi @BonkeGcobo , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



# To Highlights

- GitHub workflow has been followed :heavy_check_mark: 
- PR has a title and summary :heavy_check_mark: 
- Linters are OK :heavy_check_mark: 

## Required Changes ♻️

- [x] I think we need test suits for `Comment` and `Like` mode. From the requirements of this project, we are asked to add unit tests for the User, Post, Comment, and Like models.
- [ ] Let's kindly resolve the N+1 problem.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by BonkeGcobo** [comment]
Hello @FrederickMih 

Thank you for your review

I have solved the N+1 rule on the association between comments and post, during my previous branches
Post_1

**Comment by FrederickMih** [comment]
> Hello @FrederickMih
> 
> Thank you for your review
> 
> I have solved the N+1 rule on the association between comments and post, during my previous branches Post_1

Hi @BonkeGcobo, nice job for resolving this in your previous branches. Please also note that each milestone has its own set of requirements to fulfill. You are requested to also resolve the N+1 problem in this milestone. I don't think I'm required to switch through all your branches to find out if you did that.

Thanks :pray:

**Review by DammyShittu — APPROVED** [review]
Hi @BonkeGcobo,

## APPROVED 🟢

Great implementation of all the requirements in this milestone. 👏

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
